export const PRODUCT_LIST_REQUESTED = 'PRODUCT_LIST_REQUESTED';
export const PRODUCT_LIST_SUCCEEDED = 'PRODUCT_LIST_SUCCEEDED';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';
export const PRODUCT_DETAILS_REQUESTED = 'PRODUCT_DETAILS_REQUESTED';
export const PRODUCT_DETAILS_SUCCEEDED = 'PRODUCT_DETAILS_SUCCEEDED';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';
